version: "3.8"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  mongo_data:
